//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctfw.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int id { get; set; }
        public string username { get; set; }
        public string comment { get; set; }
        public System.DateTime comment_date { get; set; }
        public int complaint_id { get; set; }
        public string comment_answer { get; set; }
        public int user_id { get; set; }
        public bool notification { get; set; }
    
        public virtual Complaints Complaints { get; set; }
        public virtual Users Users { get; set; }
    }
}
